// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAB67QpYZLiF9HbxYT3Ul5YoW__4aoy8hA',
    appId: '1:17012376065:web:11adda75a1cccc3b80f600',
    messagingSenderId: '17012376065',
    projectId: 'diagnozapp-96805',
    authDomain: 'diagnozapp-96805.firebaseapp.com',
    storageBucket: 'diagnozapp-96805.firebasestorage.app',
    measurementId: 'G-52MQLH3SE8',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwuLh-acrCJhbRoqnl0DFT6g-3Ko7oSJU',
    appId: '1:17012376065:ios:9b413d068684ff6580f600',
    messagingSenderId: '17012376065',
    projectId: 'diagnozapp-96805',
    storageBucket: 'diagnozapp-96805.firebasestorage.app',
    iosBundleId: 'com.example.diagnozApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwuLh-acrCJhbRoqnl0DFT6g-3Ko7oSJU',
    appId: '1:17012376065:ios:9b413d068684ff6580f600',
    messagingSenderId: '17012376065',
    projectId: 'diagnozapp-96805',
    storageBucket: 'diagnozapp-96805.firebasestorage.app',
    iosBundleId: 'com.example.diagnozApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAB67QpYZLiF9HbxYT3Ul5YoW__4aoy8hA',
    appId: '1:17012376065:web:4db3b9088a7b0f5d80f600',
    messagingSenderId: '17012376065',
    projectId: 'diagnozapp-96805',
    authDomain: 'diagnozapp-96805.firebaseapp.com',
    storageBucket: 'diagnozapp-96805.firebasestorage.app',
    measurementId: 'G-48PRMC4V37',
  );

}